### ISSUE TITLE
PlayerChunkMap Cause MemoryLeak

### ISSUE THREAD

**Issue by murat716** [froobynooby/ViewDistanceTweaks#10]
A few days after run the server, the Player Chunk Map object causing a memory leak problem. Probably this issue from ViewDistanceTweaks.

**Comment by froobynooby** [comment]
Hey, could you share the output of `/version` and possibly a timings report?

**Comment by murat716** [comment]
It's memory leak, not showing in timings. I'm used eclipse memory analyzer tool to find this. Also my server crashing after to many player joined the server. I think it's caused from ViewDistanceTweaks.

[2021-04-09-1.log.gz](https://github.com/froobynooby/ViewDistanceTweaks/files/6277912/2021-04-09-1.log.gz)

**Comment by froobynooby** [comment]
Are you sure it's a memory leak and not just PlayerChunkMap taking up a lot of memory? If so I'd recommend asking for help in the Tuinity discord. The plugin uses the view distance API when setting the view distance, so it's unlikely to be causing any memory leaks

Probably better off asking in the Tuinity discord for help with your log too. Looks like it's dying while trying to tick a player
