### ISSUE TITLE
[Feature Request] Player Based No Tick View Distance

### ISSUE THREAD

**Issue by murat716** [froobynooby/ViewDistanceTweaks#12]
I want to give view distance based online count. It's better practice than tps based view distance.

**Comment by froobynooby** [comment]
Hey, the plugin's proactive mode adjusts the view distance based on the number of player-loaded chunks. This is essentially the same as adjusting based on the number of players, but with the advantage that it takes into account if, for example, there are two players standing in the same chunk. For the no-tick view distance in particular, there is no option to adjust this based on TPS/MSPT - it can only be adjusted proactively
