### ISSUE TITLE
Fabric Version?

### ISSUE THREAD

**Issue by SulpherStaer** [froobynooby/ViewDistanceTweaks#13]
This mod is awesome. Like, I have not found any other that does this. Sadly its not compatible with fabric, and cardboard isn't playing nice.

How difficult would it be to port this for fabric?

**Comment by froobynooby** [comment]
Hey, glad you like the plugin!

I'm not too familiar with the Fabric environment, however I don't think it would be too difficult to port. The plugin largely works through hooks anyway, so it would mostly be a case of creating new hooks for Fabric servers. One thing that would be required, however, is an implementation of per-world view distances. This is a Spigot feature and I'm not sure how hard it would be to implement this on Fabric.

If I ever decide to get into Fabric modding I will definitely port the plugin over, however it's not something I am looking at right now

**Comment by SulpherStaer** [comment]
Would a commission to transpose this mod to fabric encourage you to develop it?

Both of us do not have personal identification on our github profiles, so if you are interested you could speak with me on discord.
Sulpherstær#4263

If not interested, we can close this ticket :)

**Comment by froobynooby** [comment]
I'm not interested in learning fabric at this stage, sorry, but I may want to look into it in the future. I'm sure there are places where you can find fabric mod developers who would be willing to take a commission to port the plugin though

**Comment by jayhendren** [comment]
Understandable, but darn.  There doesn't appear to be an equivalent plugin in the Fabric ecosystem at the moment.

**Comment by SulpherStaer** [comment]
There actually is. It is called ticktools. It is currently in development and is not as refined as this.

But it does the job decent enough.

I was pointed to it today, whilst I was looking for someone to port this to fabric

Edit:
Ticktools is way to basic compared to ViewDistanceTweaks.
