### ISSUE TITLE
Dynamic view distance based on whether the player is generating new chunks.

### ISSUE THREAD

**Issue by ryantheleach** [froobynooby/ViewDistanceTweaks#21]
If the player is generating new chunks, this is when TPS is most likely to drop.

It would be cool to see VDT able to proactively limit the amount of worldgen chunks being generated, BEFORE the tps starts to drop causing issues for others.

E.g. generated chunks have a view distance of X, and ungenerated chunks will not generate unless within Y.

**Comment by froobynooby** [comment]
I don't think this is possible to do in a plugin, sorry. It would need to be implemented as a server patch
