### ISSUE TITLE
[Bug] spam with Changed simulation distance of world (5 -> 6)

### ISSUE THREAD

**Issue by masmc05** [froobynooby/ViewDistanceTweaks#22]
![image](https://user-images.githubusercontent.com/63639746/152387190-df3a2d6c-e5c1-4270-90ed-ea8de0743373.png)

**Comment by masmc05** [comment]
![image](https://user-images.githubusercontent.com/63639746/152422070-ff46d0a2-ba5f-47d4-a3d4-b5d5a0a5eaa6.png)
the same output and seems like he'll newer actually switch to 6 chunks distance

**Comment by masmc05** [comment]
even if there's 0 players on the server with 0 loaded chunks (just all day spam, no matter how many players and how many lags and how many chunks loaded)

**Comment by FireController1847** [comment]
Oh whoops. I seemed to have duplicated this issue with my issue #24. I do think this is a legitimate issue though, @mastermc05

**Comment by masmc05** [comment]
> Oh whoops. I seemed to have duplicated this issue with my issue #24. I do think this is a legitimate issue though, @mastermc05

it is, because it doesn't support new versions of paper, pufferfish and purpur
