### ISSUE TITLE
Rare null pointer exception

### ISSUE THREAD

**Issue by MWHunter** [froobynooby/ViewDistanceTweaks#23]
https://gist.githubusercontent.com/MWHunter/52c8a8fca12eedcb859612f3453666c6/raw/80e5a897c04f8d55feffefbc5daa4a02900957e7/gistfile1.txt

Probably a race condition, first error for this in months of running this plugin.

**Comment by froobynooby** [comment]
I didn't account for plugins accessing placeholders from other threads - I'll fix this in the next update
