### ISSUE TITLE
Error when enabling plugin

### ISSUE THREAD

**Issue by srnyx** [froobynooby/ViewDistanceTweaks#28]
https://paste.srnyx.xyz/peciqagawu.properties

**Comment by froobynooby** [comment]
You'll need to be using version 1.5.0 in 1.18.2 - version 1.4.0 is not compatible

**Comment by srnyx** [comment]
> You'll need to be using version 1.5.0 in 1.18.2 - version 1.4.0 is not compatible

What the heck how did I not download 1.5.0?! I swear I had downloaded the latest... so weird. Sorry!
