### ISSUE TITLE
Doesn't work on paper 1.16.3

### ISSUE THREAD

**Issue by Ayon224** [froobynooby/ViewDistanceTweaks#3]

**Comment by froobynooby** [comment]
Could you share your log? It seems to be working for me

**Comment by froobynooby** [comment]
I'm just going to close this for now. If the plugin is showing up in red on the `/plugins` list, it's most likely that you've forgotten to set the plugin to enabled in the config (located `plugins/ViewDistanceTweaks/config.yml`)
