### ISSUE TITLE
View distance and simulation distance rising itself

### ISSUE THREAD

**Issue by MegalithOfficial** [froobynooby/ViewDistanceTweaks#30]
![image](https://user-images.githubusercontent.com/74655120/163541897-45b856a3-699d-4e4a-8165-3b97bffb4ed5.png)
the view and simulaiton distance rising itself, Is it normal?

**Comment by froobynooby** [comment]
Yes the plugin will automatically adjust the view and simulation distances up if it thinks your server has the extra capacity to do so
