### ISSUE TITLE
View distance isn't changing

### ISSUE THREAD

**Issue by dbrighthd** [froobynooby/ViewDistanceTweaks#31]
even at 50 MSPT when my min MSPT for decreasing distance at 30, my view-distance is stuck at 10.

![image](https://user-images.githubusercontent.com/68525639/164377965-79307613-dd66-4b20-bc3b-884560d982fd.png)

these are my view distance settings.

the simulation distance is changing though

**Comment by froobynooby** [comment]
The wording in the config isn't great, but this is how the plugin is meant to work. Only the simulation distance will be decreased/increased in line with MSPT, whereas the view distance is only ever adjusted based on the number of loaded chunks. This is to acknowledge the relatively small impact view distance has on MSPT in comparison to simulation distance

**Comment by dbrighthd** [comment]
I understand, but after manually turning down view distance with a command, the mspt did improve noticeably

**Comment by imDaniX** [comment]
It actually does have major impact when set to 10+ values on a server with players actively moving, especially on a host with rather small amount of cores. I'd actually like to have an option to turn view distance adjustment on when using reactive mode. Pretty please?

**Comment by froobynooby** [comment]
I can acknowledge that loading and unloading chunks, regardless of whether they are ticking or non-ticking, does have an affect on performance. The plugin does allow you to somewhat moderate chunk loading by setting global chunk count targets, which are in the `config.yml`. Alternatively, Paper has some settings which allow you to directly rate limit chunk loading. I'd suggest playing around with these things if you are having trouble with high view distances causing performance issues to see if they help.

The plugin's reactive mode isn't really capable of adjusting both simulation distance and view distance at the same time without making some nasty assumptions as to how much simulation distance contributes to MSPT versus view distance. Without some significant refactoring of the plugin it's just not possible to adjust view distance in response to MSPT in any _meaningful_ way.

Feel free to open a separate issue as a feature request for potential future consideration, but it's not on the plate at the moment, sorry
