### ISSUE TITLE
No worlds matched predicate

### ISSUE THREAD

**Issue by FreddyBendy** [froobynooby/ViewDistanceTweaks#46]
Server is on 1.19.2 Mohist (78)
When i type the following command
/vdt viewdistance 28
this just pops up [Server thread/INFO] [/]: No worlds matched predicate.
Thr plugin is enabled, vdt reload works, but it seems like it cant find the world even tho theres only the Overworld and nether (Name of the world is "world")
Also i tried /vdt viewdistance 28 world 120

**Comment by froobynooby** [comment]
The command seems to be working okay for me
```
> vdt viewdistance 28
[21:18:34 INFO]: Set view distance of world_nether, world_the_end, world to 28 until next reload.
```

If you're using a duration in the command you need to include the `--duration` flag, for example: `/vdt viewdistance 28 world --duration 120`. If you use the last command you provided the plugin will look for a world called "world 120", which it won't be able to find
