### ISSUE TITLE
Please Update to 1.21

### ISSUE THREAD

**Issue by LeonMT1** [froobynooby/ViewDistanceTweaks#62]
The Plugin isnt working in newer Versions.

**Comment by Chevels** [comment]
This plugin is a must have, it's definitely worth maintaining and it would be great if it was updated for 1.21!

**Comment by Matrakalero** [comment]
pls

**Comment by mxlt02** [comment]
pls

**Comment by Learting** [comment]
true, in 1.21 not only are there ERRORs that are like swiping the screen, but the player client often reloads the map whenever VDT has changed. Please update it, many thanks

**Comment by froobynooby** [comment]
https://ci.froobworld.com/job/ViewDistanceTweaks/16/
