### ISSUE TITLE
Terrain refreshes every few seconds on 1.21 with client view distance higher than VDT

### ISSUE THREAD

**Issue by nuttapillar** [froobynooby/ViewDistanceTweaks#63]
Hi, I was running the latest build of this on a paper 1.21 server. If they had their render distance set to 1 less, the same or higher than the current distance set by VDT, their terrain would frequently flash/refresh.
But if they set their view distance to less than 1 lower than VDT, it would run fine.

**Comment by froobynooby** [comment]
https://ci.froobworld.com/job/ViewDistanceTweaks/16/
