### ISSUE TITLE
Error when join 1.21

### ISSUE THREAD

**Issue by moda84** [froobynooby/ViewDistanceTweaks#64]
![изображение](https://github.com/user-attachments/assets/a36d43ba-7105-4de3-b9b3-f0a024f06315)
If player join - error in console
Plugin version: 1.5.7
Server version: This server is running Paper version 1.21-81-master@ceeb8c1 (2024-07-17T00:39:18Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Comment by Alulom** [comment]
you can use latest devbuild to fix this, however there are still some issues like " Could not pass event PlayerJoinEvent to ViewDistanceTweaks v1.5.7" so plugin doesnt fully support  1.21 and 1.20.6 yet
